apiVersion: v1
kind: Namespace
metadata:
  name: actimize-actone
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ss
  namespace: actimize-actone
  labels:
    app: nginx-ss
spec:
  clusterIP: None
  selector:
    app: nginx-ss
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-ss
  namespace: actimize-actone
spec:
  serviceName: "nginx-ss"
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ss
  template:
    metadata:
      labels:
        app: nginx-ss
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: html
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
